'use client'
import { useEffect, useMemo, useState } from 'react'
import { Search, SlidersHorizontal, Sparkles } from 'lucide-react'
import { api } from '@/lib/api'
import { getErrorMessage } from '@/lib/api-error'
import type { Court } from '@/lib/types'
import { CourtCard } from '@/components/court-card'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { toast } from 'sonner'
const types = ['Tất cả', 'Bóng đá', 'Cầu lông', 'Tennis', 'Pickleball', 'Bóng rổ']
export default function CourtsPage() { const [courts, setCourts] = useState<Court[]>([]); const [query, setQuery] = useState(''); const [type, setType] = useState('Tất cả'); const [loading, setLoading] = useState(true); useEffect(() => { api.courts().then(setCourts).catch(e => toast.error(getErrorMessage(e))).finally(() => setLoading(false)) }, []); const filtered = useMemo(() => courts.filter(c => c.name.toLowerCase().includes(query.toLowerCase()) && (type === 'Tất cả' || c.type === type)), [courts, query, type]); return <div><section className="bg-primary px-4 py-14 text-primary-foreground sm:py-20"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><Badge className="mb-4 border-0 bg-white/15 text-white"><Sparkles /> Đặt sân thật dễ</Badge><h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Tìm sân, đặt lịch,<br /><span className="text-emerald-200">chơi hết mình.</span></h1><p className="mt-4 max-w-lg text-base text-emerald-50/80">Khám phá những sân thể thao chất lượng quanh bạn và đặt lịch chỉ trong vài thao tác.</p></div><div className="relative mt-8 max-w-xl"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tìm theo tên sân..." className="h-14 border-0 bg-white pl-12 text-foreground shadow-xl placeholder:text-muted-foreground" /></div></div></section><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="sticky top-16 z-30 -mx-4 mb-7 border-b bg-slate-50/95 px-4 py-4 backdrop-blur sm:-mx-6 sm:px-6"><div className="flex items-center gap-2 overflow-x-auto"><SlidersHorizontal className="size-4 shrink-0 text-muted-foreground" />{types.map(t => <button key={t} onClick={() => setType(t)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-sm font-medium transition ${type === t ? 'border-primary bg-primary text-primary-foreground' : 'bg-background text-muted-foreground hover:border-primary hover:text-primary'}`}>{t}</button>)}</div></div><div className="mb-7"><p className="text-sm font-medium text-primary">KHÁM PHÁ ĐỊA ĐIỂM</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Sân thể thao gần bạn</h2></div>{loading ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Skeleton className="h-72 rounded-2xl" /><Skeleton className="h-72 rounded-2xl" /><Skeleton className="h-72 rounded-2xl" /></div> : filtered.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(c => <CourtCard key={c.id} court={c} />)}</div> : <div className="rounded-2xl border border-dashed bg-background px-6 py-16 text-center"><h3 className="text-lg font-semibold">Không tìm thấy sân phù hợp</h3><p className="mt-2 text-sm text-muted-foreground">Thử đổi từ khóa hoặc bộ lọc để xem thêm địa điểm.</p></div>}</section></div> }
