'use client'
import { createContext, useContext, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { api } from '@/lib/api'
import type { Session, User } from '@/lib/types'
type AuthContextValue = { user: User | null; loading: boolean; login: (email: string, password: string) => Promise<User>; register: (data: { email: string; password: string; name: string }) => Promise<User>; logout: () => void; refresh: () => Promise<void> }
const AuthContext = createContext<AuthContextValue | null>(null)
export function AuthProvider({ children }: { children: React.ReactNode }) { const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true); const router = useRouter(); useEffect(() => { const raw = localStorage.getItem('sfb_session'); if (raw) { const session = JSON.parse(raw) as Session; setUser(session.user) } setLoading(false) }, []); const login = async (email: string, password: string) => { const { access_token } = await api.login(email, password); const next = await api.me(); localStorage.setItem('sfb_token', access_token); localStorage.setItem('sfb_user', JSON.stringify(next)); localStorage.setItem('sfb_session', JSON.stringify({ token: access_token, user: next })); setUser(next); return next }; const register = async (data: { email: string; password: string; name: string }) => { await api.register(data); return login(data.email, data.password) }; const logout = () => { localStorage.removeItem('sfb_token'); localStorage.removeItem('sfb_user'); localStorage.removeItem('sfb_session'); setUser(null); router.push('/login') }; const refresh = async () => { const next = await api.me(); setUser(next); localStorage.setItem('sfb_user', JSON.stringify(next)) }; return <AuthContext.Provider value={{ user, loading, login, register, logout, refresh }}>{children}</AuthContext.Provider> }
export function useAuth() { const context = useContext(AuthContext); if (!context) throw new Error('useAuth must be used within AuthProvider'); return context }
